VirtoCommerce/vc-module-pricing

VirtoCommerce.PricingModule.Data/Services/PricingSearchServiceImpl.cs
Search results is not restricted by keyword as the result
=> Linq query result is not assigned to variable

VirtoCommerce.PricingModule.Data/Services/PricingSearchServiceImpl.cs, VirtoCommerce.PricingModule.Data/VirtoCommerce.PricingModule.Data.csproj, VirtoCommerce.PricingModule.Data/packages.config, VirtoCommerce.PricingModule.Test/VirtoCommerce.PricingModule.Test.csproj, VirtoCommerce.PricingModule.Test/packages.config, VirtoCommerce.PricingModule.Web/VirtoCommerce.PricingModule.Web.csproj, VirtoCommerce.PricingModule.Web/packages.config
Checks if modified date is entered in searchcriteria and adds predicate.
=> Added modified predicate.

VirtoCommerce.PricingModule.Data/Services/PricingServiceImpl.cs, VirtoCommerce.PricingModule.Test/PriceScenarios.cs, VirtoCommerce.PricingModule.Test/VirtoCommerce.PricingModule.Test.csproj, VirtoCommerce.PricingModule.Test/packages.config
EvaluateProductPrices fixed to respect quantities;
PriceLists sorting fixed
=> EvaluateProductPrices fixed to respect quantities;

VirtoCommerce.PricingModule.Web/Scripts/blades/item/item-prices.js, VirtoCommerce.PricingModule.Web/Scripts/blades/item/item-prices.tpl.html, VirtoCommerce.PricingModule.Web/Scripts/blades/pricelist-detail.tpl.html, VirtoCommerce.PricingModule.Web/Scripts/blades/prices-list.js, VirtoCommerce.PricingModule.Web/Scripts/blades/prices-list.tpl.html
- Datepicker for from/till price editing table.
- Cleanup price list detail controls.
=> Delaware pro features/from till prices - Datepicker

VirtoCommerce.PricingModule.Data/Services/DefaultPricingPriorityFilterPolicy.cs, VirtoCommerce.PricingModule.Data/Services/PricingServiceImpl.cs, VirtoCommerce.PricingModule.Test/PriceScenarios.cs
=> Price date filtering tests + small tweaks

VirtoCommerce.PricingModule.Web/Scripts/blades/pricelist-item-list.js, VirtoCommerce.PricingModule.Web/Scripts/widgets/itemPricesWidget.js
=> #47 Currency filter for price range and product price widget should use global settings defined in platform

VirtoCommerce.PricingModule.Data/Services/PricingSearchServiceImpl.cs
=> Paged search ordering revision

VirtoCommerce.PricingModule.Data/ExportImport/PriceExportPagedDataSource.cs, VirtoCommerce.PricingModule.Data/ExportImport/PricelistAssignmentExportPagedDataSource.cs, VirtoCommerce.PricingModule.Data/ExportImport/PricelistExportPagedDataSource.cs, VirtoCommerce.PricingModule.Web/Scripts/blades/assignment-list.js, VirtoCommerce.PricingModule.Web/Scripts/blades/pricelist-item-list.js, VirtoCommerce.PricingModule.Web/Scripts/blades/pricelist-list.js
remove isTabularExportSupported
fix lost data query keyword 
fix isAllSelected handler
=> vp-525 Fix inconsistencies in pricing export

src/VirtoCommerce.PricingModule.Web/Module.cs
https://virtocommerce.atlassian.net/browse/VP-555
=> #vp555 Pricing facet search fix

VirtoCommerce.PricingModule.Web/Module.cs, VirtoCommerce.PricingModule.Web/module.manifest
Add the new setting Pricing.Search.EventBasedIndexation.Enable that will allows to switch on/off the event-based indexation behavior
https://github.com/VirtoCommerce/vc-module-pricing/issues/67
=> 67 - Allow to disable event-based indexation 

src/VirtoCommerce.PricingModule.Core/Model/PricelistAssignment.cs, src/VirtoCommerce.PricingModule.Core/VirtoCommerce.PricingModule.Core.csproj, src/VirtoCommerce.PricingModule.Data/VirtoCommerce.PricingModule.Data.csproj, tests/VirtoCommerce.PricingModule.Test/VirtoCommerce.PricingModule.Test.csproj
=> Nugets updating

src/VirtoCommerce.PricingModule.Data/Repositories/PricingRepositoryImpl.cs
https://virtocommerce.atlassian.net/browse/VP-1274
=> #VP-1274 fix delete pricelist

src/VirtoCommerce.PricingModule.Web/Controllers/Api/PricingModuleController.cs
- Migrated changes from v2: https://github.com/VirtoCommerce/vc-module-pricing/pull/75. Added POST endpoint to bypass search criteria without GET reuqest restrictions;
=> VP-1850: Allow to search prices using POST request

src/VirtoCommerce.PricingModule.Web/Scripts/blades/assignment-list.js, src/VirtoCommerce.PricingModule.Web/Scripts/blades/item/item-pricelists-list.js, src/VirtoCommerce.PricingModule.Web/Scripts/blades/item/item-prices.js, src/VirtoCommerce.PricingModule.Web/Scripts/selectors/catalog-selector.js
Change getCatalogs endpoint to search endpoint.
=> VP-2065 Fix price blade error when in platform registered more than 20

src/VirtoCommerce.PricingModule.Core/VirtoCommerce.PricingModule.Core.csproj, src/VirtoCommerce.PricingModule.Data/Common/ModuleConfigurator.cs, src/VirtoCommerce.PricingModule.Data/Handlers/ObjectSettingEntryChangedEventHandler.cs, src/VirtoCommerce.PricingModule.Data/VirtoCommerce.PricingModule.Data.csproj, src/VirtoCommerce.PricingModule.Web/Localizations/en.VirtoCommerce.Pricing.json, src/VirtoCommerce.PricingModule.Web/Module.cs, src/VirtoCommerce.PricingModule.Web/VirtoCommerce.PricingModule.Web.csproj
https://virtocommerce.atlassian.net/browse/VP-2354
=> Refactor to apply setting values immediately #VP-2354

src/VirtoCommerce.PricingModule.Data/Handlers/IndexPricesProductChangedEventHandler.cs, src/VirtoCommerce.PricingModule.Web/Localizations/en.VirtoCommerce.Pricing.json, src/VirtoCommerce.PricingModule.Web/Module.cs
https://virtocommerce.atlassian.net/browse/VP-2402
=> Apply EventBasedIndexation setting value immediately #VP-2402

src/VirtoCommerce.PricingModule.Data/Search/ProductPriceDocumentBuilder.cs
This field has a value of "sale" if at least one PriceList has a Sale more than 0.
=> Added new sale field to the product index

VirtoCommerce.PricingModule.Web/module.manifest
https://virtocommerce.atlassian.net/browse/VP-3122
=> VP-3122: Fix logo

src/VirtoCommerce.PricingModule.Web/Scripts/blades/prices-list.js
https://virtocommerce.atlassian.net/browse/VP-5268
=> #VP-5268 refresh after editing

src/VirtoCommerce.PricingModule.Web/Localizations/en.VirtoCommerce.Pricing.json, src/VirtoCommerce.PricingModule.Web/Scripts/blades/pricelist-item-list.js, src/VirtoCommerce.PricingModule.Web/Scripts/blades/pricelist-item-list.tpl.html
https://virtocommerce.atlassian.net/browse/VP-5265
Add default product name if product do not exist for selected price
=> VP-5265: Fix error when price without product

src/VirtoCommerce.PricingModule.Web/Scripts/blades/assignment-list.tpl.html, src/VirtoCommerce.PricingModule.Web/Scripts/blades/pricelist-detail.tpl.html, src/VirtoCommerce.PricingModule.Web/Scripts/blades/pricelist-list.tpl.html
=> VP-5512: Change color of Edit and Delete icon to common style

src/VirtoCommerce.PricingModule.Core/ModuleConstants.cs, src/VirtoCommerce.PricingModule.Core/VirtoCommerce.PricingModule.Core.csproj, src/VirtoCommerce.PricingModule.Data/VirtoCommerce.PricingModule.Data.csproj, src/VirtoCommerce.PricingModule.Web/VirtoCommerce.PricingModule.Web.csproj, src/VirtoCommerce.PricingModule.Web/module.manifest
Related to https://github.com/VirtoCommerce/vc-platform/pull/2090
Jira: https://virtocommerce.atlassian.net/browse/VP-5673
=> VP-5673: Fix page size positive only

src/VirtoCommerce.PricingModule.Web/Scripts/blades/pricelist-list.js
VP-1313 Filter pricelists after clear filter and reload page
Clear local storage
=> VP-1313: Clear filter when clear button pressed 

src/VirtoCommerce.PricingModule.Web/Scripts/blades/assignment-detail.js, src/VirtoCommerce.PricingModule.Web/Scripts/blades/assignment-list.js, src/VirtoCommerce.PricingModule.Web/Scripts/blades/assignment-list.tpl.html, src/VirtoCommerce.PricingModule.Web/Scripts/blades/item/item-prices.js, src/VirtoCommerce.PricingModule.Web/Scripts/blades/pricelist-detail.js, src/VirtoCommerce.PricingModule.Web/Scripts/blades/pricelist-item-list.js, src/VirtoCommerce.PricingModule.Web/Scripts/blades/pricelist-item-list.tpl.html, src/VirtoCommerce.PricingModule.Web/Scripts/blades/pricelist-list.js, src/VirtoCommerce.PricingModule.Web/Scripts/blades/pricelist-list.tpl.html, src/VirtoCommerce.PricingModule.Web/Scripts/blades/prices-list.js
=> VP-6366: Replace panel action icons

src/VirtoCommerce.PricingModule.Web/Scripts/blades/assignment-list.js, src/VirtoCommerce.PricingModule.Web/Scripts/blades/item/item-pricelists-list.js, src/VirtoCommerce.PricingModule.Web/Scripts/blades/pricelist-list.js, src/VirtoCommerce.PricingModule.Web/Scripts/blades/pricing-main.js, src/VirtoCommerce.PricingModule.Web/Scripts/blades/pricing-main.tpl.html
Use font awesome in the right way
=> VP-6768: Security section Replace Key icon

src/VirtoCommerce.PricingModule.Data/Services/PricingSearchServiceImpl.cs, src/VirtoCommerce.PricingModule.Web/Scripts/blades/assignment-detail.js, src/VirtoCommerce.PricingModule.Web/Scripts/blades/assignment-detail.tpl.html, src/VirtoCommerce.PricingModule.Web/Scripts/directives/uiScroll.js, src/VirtoCommerce.PricingModule.Web/Scripts/directives/uiScroll.tpl.html
Add infinite scroll for selectors
Enable search for pricelist by objectIds
=> VP-6852 Add infinite scroll for catalog and priselist selectors

src/VirtoCommerce.PricingModule.Web/Scripts/blades/assignment-detail.tpl.html
=> VP-7111: Field priority not shown in price list assignment details

src/VirtoCommerce.PricingModule.Web/Module.cs
https://virtocommerce.atlassian.net/browse/VP-6905
=> VP-6905 remove call to BuildServiceProvider

src/VirtoCommerce.PricingModule.Data/ExportImport2/ExportablePrice.cs, src/VirtoCommerce.PricingModule.Data/ExportImport2/TabularPrice.cs, src/VirtoCommerce.PricingModule.Web/Content/css/pricing.css, src/VirtoCommerce.PricingModule.Web/Localizations/en.VirtoCommerce.Pricing.json, src/VirtoCommerce.PricingModule.Web/Localizations/ru.VirtoCommerce.Pricing.json, src/VirtoCommerce.PricingModule.Web/Scripts/blades/pricelist-item-list.js, src/VirtoCommerce.PricingModule.Web/Scripts/dialogs/priceExport-dialog.tpl.html
Based on https://github.com/VirtoCommerce/vc-module-pricing/pull/128
All changes for this user story are in the last 2 commits
=> VDS-663: Show validation error for pricing export

src/VirtoCommerce.PricingModule.Data/ExportImport2/ExportablePrice.cs, src/VirtoCommerce.PricingModule.Data/ExportImport2/TabularPrice.cs, src/VirtoCommerce.PricingModule.Web/Content/css/pricing.css, src/VirtoCommerce.PricingModule.Web/Localizations/en.VirtoCommerce.Pricing.json, src/VirtoCommerce.PricingModule.Web/Localizations/ru.VirtoCommerce.Pricing.json, src/VirtoCommerce.PricingModule.Web/Scripts/blades/pricelist-item-list.js, src/VirtoCommerce.PricingModule.Web/Scripts/dialogs/priceExport-dialog.tpl.html
Export module artifact with delimiter fix: https://devsteamsta.blob.core.windows.net/solution/VirtoCommerce.Export_3.11.0.zip
=> VDS-658: Run simple export from the price list

src/VirtoCommerce.PricingModule.Core/Events/PricelistAssignmentChangedEvent.cs, src/VirtoCommerce.PricingModule.Core/Events/PricelistAssignmentChangingEvent.cs, src/VirtoCommerce.PricingModule.Core/Events/PricelistChangedEvent.cs, src/VirtoCommerce.PricingModule.Core/Events/PricelistChangingEvent.cs, src/VirtoCommerce.PricingModule.Data/Services/PricingServiceImpl.cs, src/VirtoCommerce.PricingModule.Web/module.manifest
Reverts VirtoCommerce/vc-module-pricing#137
=> PT-1000: Changing, Changed events about Pricelist and Pricelist Assignments (From revert)

src/VirtoCommerce.PricingModule.Data/Services/PricingSearchServiceImpl.cs, src/VirtoCommerce.PricingModule.Web/Localizations/en.VirtoCommerce.Pricing.json, src/VirtoCommerce.PricingModule.Web/Scripts/blades/pricelist-item-list.js, src/VirtoCommerce.PricingModule.Web/Scripts/blades/pricelist-item-list.tpl.html, src/VirtoCommerce.PricingModule.Web/Scripts/blades/prices-list.js
https://virtocommerce.atlassian.net/browse/PT-489
=> PT-490: Fix prices grouping and display in UI

src/VirtoCommerce.PricingModule.Web/Scripts/blades/pricelist-item-list.js
These changes were made in order to use advanced export functionality in other modules. Advanced export functionality works as before
=> VDS-1720: Implement changes to pricelistItemListController

src/VirtoCommerce.PricingModule.Web/Scripts/blades/assignment-list.tpl.html, src/VirtoCommerce.PricingModule.Web/Scripts/blades/pricelist-item-list.tpl.html, src/VirtoCommerce.PricingModule.Web/Scripts/blades/pricelist-list.tpl.html, src/VirtoCommerce.PricingModule.Web/module.manifest
https://virtocommerce.atlassian.net/browse/PT-635
Old and updated UI:
=> PT-1978: Redesign search UI

src/VirtoCommerce.PricingModule.Data/Repositories/PricingRepositoryImpl.cs, src/VirtoCommerce.PricingModule.Web/Controllers/Api/PricingModuleController.cs
https://virtocommerce.atlassian.net/browse/PT-824
=> PT-825: Fix price lists assignments enumeration on delete

docs/add-new-assignment.md, docs/export-functionality.md, docs/managing-pricing-module-settings.md
=> PT-2637 fix docs broken links

src/VirtoCommerce.PricingModule.Core/ModuleConstants.cs
Extend setting with System attribute/flag
https://virtocommerce.atlassian.net/browse/PT-2767
=> PT-2767: Extend setting with System attribute/flag

src/VirtoCommerce.PricingModule.Web/Controllers/Api/PricingModuleController.cs, src/VirtoCommerce.PricingModule.Web/VirtoCommerce.PricingModule.Web.csproj, src/VirtoCommerce.PricingModule.Web/module.manifest
Use assets from newly created module instead of the platform
https://virtocommerce.atlassian.net/browse/PT-4135
=> PT-4135: Use assets from newly created module instead of the platform

src/VirtoCommerce.PricingModule.Core/Model/PriceEvaluationContext.cs, src/VirtoCommerce.PricingModule.Data/Search/ProductPriceDocumentBuilder.cs, src/VirtoCommerce.PricingModule.Data/Services/PricingEvaluatorService.cs
Price lists with dynamicExpression are not indexed
https://virtocommerce.atlassian.net/browse/PT-5719
=> PT-5719: Price lists with dynamicExpression are not indexed

src/VirtoCommerce.PricingModule.Web/Scripts/blades/item/item-prices.js
=> PT-6313: Fix script error when adding new price to product

src/VirtoCommerce.PricingModule.Data/Search/ProductPriceDocumentBuilder.cs
Fix product price sorting
https://virtocommerce.atlassian.net/browse/PT-6125
=> PT-6125: Fix price sorting

src/VirtoCommerce.PricingModule.Core/VirtoCommerce.PricingModule.Core.csproj, src/VirtoCommerce.PricingModule.Data/VirtoCommerce.PricingModule.Data.csproj, src/VirtoCommerce.PricingModule.Web/VirtoCommerce.PricingModule.Web.csproj
https://virtocommerce.atlassian.net/browse/PT-6404
=> PT-6404: Fix empty sonar codecoverage report

src/VirtoCommerce.PricingModule.Data/Validators/PriceListValidator.cs, src/VirtoCommerce.PricingModule.Web/Controllers/Api/PricingModuleController.cs, src/VirtoCommerce.PricingModule.Web/Module.cs
Pricelists validation is added
https://virtocommerce.atlassian.net/browse/PT-7048
=> PT-7048: Pricelists validation is added

src/VirtoCommerce.PricingModule.Data/Validators/PriceListValidator.cs
Description validation is fixed for the null value
=> PT-7566: Description validation is fixed for the null value

src/VirtoCommerce.PricingModule.Core/Model/PriceEvaluationContext.cs, src/VirtoCommerce.PricingModule.Core/Model/PriceList.cs, src/VirtoCommerce.PricingModule.Data/Services/DefaultPricingPriorityFilterPolicy.cs, src/VirtoCommerce.PricingModule.Data/Services/PricingEvaluatorService.cs, tests/VirtoCommerce.PricingModule.Test/PriceScenarios.cs
Filter prices with equal priority by price amount
https://virtocommerce.atlassian.net/browse/PT-7874 https://virtocommerce.atlassian.net/jira/software/projects/PT/boards/105/backlog?selectedIssue=PT-7874
=> PT-7874: Filter prices with equal priority by price amount

src/VirtoCommerce.PricingModule.Web/Localizations/en.VirtoCommerce.Pricing.json, src/VirtoCommerce.PricingModule.Web/Scripts/blades/assignment-list.js
https://virtocommerce.atlassian.net/browse/PT-5837
=> PT-5837: Rename 'Delete all filtered' button

src/VirtoCommerce.PricingModule.Web/Localizations/en.VirtoCommerce.Pricing.json, src/VirtoCommerce.PricingModule.Web/Scripts/blades/assignment-list.js
https://virtocommerce.atlassian.net/browse/PT-5837
=> PT-5837: Fix confirm window localization

src/VirtoCommerce.PricingModule.Web/Scripts/blades/assignment-detail.tpl.html
https://virtocommerce.atlassian.net/browse/PT-634
=> PT-634: Update calendar icons

src/VirtoCommerce.PricingModule.Core/Model/MergedPrice.cs, src/VirtoCommerce.PricingModule.Core/Model/MergedPriceGroup.cs, src/VirtoCommerce.PricingModule.Core/Model/MergedPriceGroupState.cs, src/VirtoCommerce.PricingModule.Core/Model/MergedPriceState.cs, src/VirtoCommerce.PricingModule.Core/Model/Search/MergedPriceGroupSearchResult.cs, src/VirtoCommerce.PricingModule.Core/Model/Search/MergedPriceSearchCriteria.cs, src/VirtoCommerce.PricingModule.Core/Model/Search/MergedPriceSearchResult.cs, src/VirtoCommerce.PricingModule.Core/Services/IMergedPriceSearchService.cs, src/VirtoCommerce.PricingModule.Data/Model/MergedPriceEntity.cs, src/VirtoCommerce.PricingModule.Data/Model/MergedPriceGroupEntity.cs, src/VirtoCommerce.PricingModule.Data/Repositories/IPricingRepository.cs, src/VirtoCommerce.PricingModule.Data/Repositories/PricingDbContext.cs, src/VirtoCommerce.PricingModule.Data/Repositories/PricingRepositoryImpl.cs, src/VirtoCommerce.PricingModule.Data/Services/Search/MergedPriceSearchService.cs, src/VirtoCommerce.PricingModule.Web/Module.cs
https://virtocommerce.atlassian.net/browse/PT-8665
=> PT-8665: add merged prices service

src/VirtoCommerce.PricingModule.Data/Repositories/PricingDbContext.cs
Fix EF validation runtime warnings
https://virtocommerce.atlassian.net/browse/PT-9152
=> PT-9152: Fix EF validation runtime warnings

docs/index.md
=> docs: Fix demo link as per PD-131

src/VirtoCommerce.PricingModule.Web/Localizations/ru.VirtoCommerce.Pricing.json
=> Updated ru localization

src/VirtoCommerce.PricingModule.Core/ModuleConstants.cs, src/VirtoCommerce.PricingModule.Data/Search/ProductPriceDocumentBuilder.cs, src/VirtoCommerce.PricingModule.Web/Localizations/en.VirtoCommerce.Pricing.json
https://virtocommerce.atlassian.net/browse/PT-10333
=> PT-10333: add PriceIndexingValue setting

src/VirtoCommerce.PricingModule.Web/package-lock.json, src/VirtoCommerce.PricingModule.Web/package.json, src/VirtoCommerce.PricingModule.Web/webpack.config.js
feat: add nodejs-lts support
https://virtocommerce.atlassian.net/browse/PT-9395
=> PT-9395: add nodejs-lts support

src/VirtoCommerce.PricingModule.Core/Model/IndexedPrice.cs, src/VirtoCommerce.PricingModule.Core/VirtoCommerce.PricingModule.Core.csproj, src/VirtoCommerce.PricingModule.Data/Search/ProductPriceDocumentBuilder.cs, src/VirtoCommerce.PricingModule.Data/VirtoCommerce.PricingModule.Data.csproj, src/VirtoCommerce.PricingModule.Web/VirtoCommerce.PricingModule.Web.csproj, src/VirtoCommerce.PricingModule.Web/module.manifest
https://virtocommerce.atlassian.net/browse/PT-8313
=> PT-8313: index min variation price

src/VirtoCommerce.PricingModule.Data/Search/ProductPriceDocumentBuilder.cs
https://virtocommerce.atlassian.net/browse/PT-13020
https://vc3prerelease.blob.core.windows.net/packages/VirtoCommerce.Pricing_3.401.0-pr-200-7b27.zip
=> PT-13020: Implement IIndexSchemaBuilder

src/VirtoCommerce.PricingModule.Data/Search/ProductPriceDocumentBuilder.cs
https://virtocommerce.atlassian.net/browse/PT-13052
=> PT-13052: make field minVariationPrice collection and retrievable

src/VirtoCommerce.PricingModule.Core/VirtoCommerce.PricingModule.Core.csproj, src/VirtoCommerce.PricingModule.Data/Repositories/PricingDbContext.cs, src/VirtoCommerce.PricingModule.Data/VirtoCommerce.PricingModule.Data.csproj, src/VirtoCommerce.PricingModule.Web/module.manifest
fix: DateTime values coming back from the SqlServer database always have a DateTimeKind of Unspecified.
https://virtocommerce.atlassian.net/browse/PT-13179
=> PT-13179: DateTime values coming back from the SqlServer database always have a DateTimeKind of Unspecified.

src/VirtoCommerce.PricingModule.Web/Scripts/blades/assignment-list.tpl.html, src/VirtoCommerce.PricingModule.Web/Scripts/blades/pricelist-item-list.tpl.html, src/VirtoCommerce.PricingModule.Web/Scripts/blades/pricelist-list.tpl.html
feat: Remove Counter from Search panel
https://virtocommerce.atlassian.net/browse/VCST-972
https://vc3prerelease.blob.core.windows.net/packages/VirtoCommerce.Pricing_3.801.0-pr-206-a057.zip
=> VCST-972: Remove Counter from Search panel

src/VirtoCommerce.PricingModule.Data/Repositories/PricingRepositoryImpl.cs, src/VirtoCommerce.PricingModule.Data/Services/PricingEvaluatorService.cs
fix: Fix QuerySplittingBehavior.SingleQuery Warning in Pricing
https://virtocommerce.atlassian.net/browse/VCST-1383
https://vc3prerelease.blob.core.windows.net/packages/VirtoCommerce.Pricing_3.805.0-pr-209-2ab0.zip
=> VCST-1383: Fix QuerySplittingBehavior.SingleQuery Warning in Pricing

src/VirtoCommerce.PricingModule.Data/Search/ProductPriceDocumentBuilder.cs
https://virtocommerce.atlassian.net/browse/VCST-841
https://vc3prerelease.blob.core.windows.net/packages/VirtoCommerce.Pricing_3.806.0-pr-210-7b51.zip
=> VCST-841: do not index invisible variation min price

src/VirtoCommerce.PricingModule.Web/Scripts/widgets/pricesWidget.js, src/VirtoCommerce.PricingModule.Web/package-lock.json
fix: wrong total count on the prices widget
fix: bump version of some webpack packages.
https://virtocommerce.atlassian.net/browse/VCST-2482
https://vc3prerelease.blob.core.windows.net/packages/VirtoCommerce.Pricing_3.812.0-pr-215-28fd.zip
=> VCST-2482: Fix wrong total count  on widget.

src/VirtoCommerce.PricingModule.Core/Model/ProductPrice.cs, src/VirtoCommerce.PricingModule.Web/Controllers/Api/PricingModuleController.cs
feat: Added HttpPatch methods for price, Pricelist and PricelistAssignment
https://virtocommerce.atlassian.net/browse/VCST-3180
https://vc3prerelease.blob.core.windows.net/packages/VirtoCommerce.Pricing_3.814.0-pr-219-6e6e.zip
=> VCST-3180: HttpPatch methods for price, Pricelist and PricelistAssignment
